version: "3.8"
services:
  # border 注册中心
  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    restart: always
    environment:
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: "-server -Xms256m -Xmx1024m"
    ports:
      - 9876:9876
    volumes:
      - /data/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # broker 主节点
  broker-m:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker-m
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: -Duser.home=/home/rocketmq -server -Xms512m -Xmx1G -Xmn256m
      NAMESRV_ADDR: 192.168.102.50:9876;192.168.102.51:9876
    volumes:
      - /data/rocketmq/master/logs:/home/rocketmq/logs
      - /data/rocketmq/master/store:/home/rocketmq/store
      - /data/rocketmq/master/conf:/home/rocketmq/conf
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf --enable-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      - namesrv

  # broker 从节点
  broker-s:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker-s
    restart: always
    ports:
      - 11909:11909
      - 11911:11911
      - 11912:11912
    environment:
      TZ: Asia/Shanghai
      JAVA_OPT_EXT: -Duser.home=/home/rocketmq -server -Xms512m -Xmx1G -Xmn256m
      NAMESRV_ADDR: 192.168.102.50:9876;192.168.102.51:9876
    volumes:
      - /data/rocketmq/salve/logs:/home/rocketmq/logs
      - /data/rocketmq/salve/store:/home/rocketmq/store
      - /data/rocketmq/salve/conf:/home/rocketmq/conf
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf --enable-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      - namesrv
